on: [ push ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/anytypeio
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'

      - name: git config
        run: git config --global url.https://${{ secrets.ANYTYPE_PAT }}@github.com/.insteadOf https://github.com/

      # cache {{
      - id: go-cache-paths
        run: |
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.GOCACHE }}
            ${{ steps.go-cache-paths.outputs.GOMODCACHE }}
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      # }}

      - name: deps
        run: make deps

      - name: unit tests
        run: make test

      - name: build
        run: make build

      - name: debug
        run: |
          ls -al ./
          echo "${{ github }}"

      # create package {{
      - name: create package
        uses: bpicode/github-action-fpm@master
        with:
          fpm_opts: "--debug --name ${{ github.event.repository.name }} --output-type deb --version ${{ github.ref }} --input-type dir"
          fpm_args: "./bin"
      # }}

#      - name: upload-artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: any-sync-node_1.0_amd64.deb
#          path: any-sync-node_1.0_amd64.deb
#
#      - name: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ./any-sync-node_1.0_amd64.deb
#          asset_name: any-sync-node_1.0_amd64.deb
#          asset_content_type: application/octet-stream
